### ISSUE TITLE
End event registration Function 

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#17]
As an event owner, i should be able end event registration, 

Only event owner can call this function

```
    fn end_event_registration(
        ref self: TContractState, event_id: u256
    );
```
set is_closed inside event details to TRUE
and emit EndEventRegistration event 

Write unit test for this function that cover the following 
- test is_closed is set to true,
- test should panic if function call is not an owner 
- test for emitted event 

Provide an ETH

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
I will write a function that takes event_id as a parameter, check if the caller is the event owner, set the is_closed field in the event details to true, then emit an end_event_registration event. Also, I will  ensure the function verifies only when the event owner calls it, then revert it when the caller is not the owner. Test included as well.

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
A fullstack Blockchain developer, with extensive experience in building smart contracts.

### How I plan on tackling this issue
The end_event_registration function must:
    Ensure only the owner can end the registration.
    Set the is_closed field to true when the registration ends.
    Emit the EndEventRegistration event upon successful closure.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi

**Comment by Gerson2102** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
---

### Hey! I'm Gerson. 👋

Member of **Dojo Coding**. I have contributed before to other Cairo projects like:

- `Raito`
- `kakarot-ssj`

Can I work on this issue?

Check my OnlyDust profile, I've contributed to many projects: [Profile](https://app.onlydust.com/u/Gerson2102)

---

### How I plan on tackling this issue
### Plan to Solve the Issue:

1. **Study the codebase** to understand the current structure and functionality.
2. **Understand the problem** that needs to be solved by thoroughly reading the issue details.
3. **Leverage all provided resources** within the issue to get a better grasp of the task at hand.
4. If I encounter roadblocks, I will **ask questions ASAP** in the Telegram group to move forward effectively.
5. **I will open a PR** and wait for ur feedback

---

**Comment by nickgore** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, I'm data analyst / SC dev. For last half a year i ve been helping CarmineFinance improving their option AMM as well as developing new products, thus i have quite extensive hand on experience with Cairo. I would love to contribute to this issue or tackle something more challenging.


### How I plan on tackling this issue
1. Add body for `fn end_event_registration`
 - assert if caller is event owner. Owner for given event_id can be obtained from storage map`event_owners` or alernatively i can properly implement `fn event_owner` and use it)
 - update i.e set `is_closed` to true in event details for given event_id, could be found in storage `event_details` map. 
 - emit `EndEventRegistration` (event_id and owner are known by now. name can be obtained from event details.)
2. Add 3 unit test.
 - in first test we just need to add_event and use end_event_registration with same caller mock. then assert is_close in event details of given event.
 - in second test we mock different callers for  add_event and end_event_registration. -> then func will panuc due to assert
 - the same as first but instead of assert - check if appropriate event is present and check if it contains correct data

**Comment by nickgore** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).
> 
> ### My background and how it can be leveraged
> Hi, I'm data analyst / SC dev. For last half a year i ve been helping CarmineFinance improving their option AMM as well as developing new products, thus i have quite extensive hand on experience with Cairo. I would love to contribute to this issue or tackle something more challenging.
> 
> ### How I plan on tackling this issue
> 1. Add body for `fn end_event_registration`
> 
> * assert if caller is event owner. Owner for given event_id can be obtained from storage map`event_owners` or alernatively i can properly implement `fn event_owner` and use it)
> * update i.e set `is_closed` to true in event details for given event_id, could be found in storage `event_details` map.
> * emit `EndEventRegistration` (event_id and owner are known by now. name can be obtained from event details.)
> 
> 2. Add 3 unit test.
> 
> * in first test we just need to add_event and use end_event_registration with same caller mock. then assert is_close in event details of given event.
> * in second test we mock different callers for  add_event and end_event_registration. -> then func will panuc due to assert
> * the same as first but instead of assert - check if appropriate event is present and check if it contains correct data

ETA - friday morning CET

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
I will Test for the following
Valid event owner: Verify the function sets is_closed to true.
Non-event owner: Verify the function panics with the expected error message.
Emitted event: Verify the EndEventRegistration event is emitted with the correct event_id.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
 I will implement the end_event_registration function in the Events contract. This function will first verify the caller's address against the stored event owner address to ensure that only the event owner can execute this function. If the caller is verified as the owner, the function will update the is_closed field in the EventDetails struct for the specified event_id to true, indicating that registration for the event has ended. Additionally, I will emit the EndEventRegistration event to notify the system of this change. To ensure the function works as intended, I will write unit tests that cover the following scenarios: checking that is_closed is correctly set to true upon successful execution, confirming that a panic occurs if a non-owner attempts to call the function, and validating that the EndEventRegistration event is emitted with the correct parameters.

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.


### How I plan on tackling this issue
I'll create the function with all the expected functionality and ensure it functions as expected with a full test coverage.
ETA-2days

**Comment by wheval** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello @mubarak23 ,  I'm Wheval, a frontend developer. I recently graduated from a Starknet Cairo Bootcamp. This would be my first contribution to the repo. I would really love to contribute and gain more experience.

### How I plan on tackling this issue
This is how I would implement the **End Event Registration** function:

1. **Retrieve Event Owner**  
   I would write the function to take the `event_id` and read the `event_owners` from storage to get the `eventOwnerAddress`.

2. **Check Ownership**  
   The function would assert that the `caller_address` is the `eventOwnerAddress`. If it is not, the function would panic with the `NOT_OWNER` error from the `errors.cairo` module.

3. **Update Event Status**  
   The function would map the `event_id` to the event details in storage and set `is_closed` to `true`.

4. **Emit Event**  
   The function would emit the `EndEventRegistration` event.

5. **Unit Tests**  
   I would write unit tests for the following scenarios:
   - `test_end_event_registration_caller_not_owner`
   - `test_end_event_registration_is_closed`
   - `test_end_event_for_emitted_event`

6. **Ensure Tests Pass**  
   I would ensure all tests pass before making a pull request.

ETA is 1 day.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I  am a frontend and blockchain developer . My background in smart contract development and testing positions me to effectively implement and validate this functionality.

### How I plan on tackling this issue
To implement the `end_event_registration` function, I would define it in the smart contract to allow only the event owner to call it. This function would set the `is_closed` property in the event details to `true` and emit an `EndEventRegistration` event. I would then write unit tests to ensure that the `is_closed` property is correctly set to `true`, that the function panics if called by someone who is not the event owner, and that the `EndEventRegistration` event is emitted upon successful execution. Additionally, I would provision the necessary ETH in the testing environment to simulate real-world conditions.

**Comment by mubarak23** [comment]
@GoSTEAN do you have an update on this issues

**Comment by GoSTEAN** [comment]
@mubarak23 a PR will be ready by today

**Comment by mubarak23** [comment]
@GoSTEAN  can you provide an update on this issue

**Comment by GoSTEAN** [comment]
@mubarak23 I Created a PR since.
