### ISSUE TITLE
Function that Return Event Organizer

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#20]
Given an event id, the function should return the event owner

`fn event_owner(self: @TContractState, event_id: u256) -> ContractAddress;`

edge case:
function should panic for wrong event_id

Write unit test for 
- event_owner function
- should panic test for wrong event_id

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
I will write a function that accepts an event_id as a parameter and retrieves the event owner's address from the event_owners storage map, then make sure the function returns the address of the event owner associated with the specified event_id. Finally, write the test.

**Comment by anonfedora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
A fullstack Blockchain developer, with extensive experience in building Web3 dApps, governance systems using smart contracts.

### How I plan on tackling this issue
The task requires creating a function implementation for the smart contract in Cairo for handling events, where each event has an owner associated with it. 
Given an event_id, the contract must return the corresponding owner. The solution also requires a unit test to ensure the function behaves as expected.

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I have a background in developing decentralized applications with Cairo for smart contracts on the StarkNet blockchain. I am experienced in building and deploying contracts and have a solid understanding of event-driven programming. I am familiar with Cairo testing and use of cairo cheatsheat, allowing me to write comprehensive tests that ensure contract reliability and security.

### How I plan on tackling this issue
To implement a function that returns the owner of an event by its eventId, I would first review the codebase to understand how events and their owners are stored. After examining the data structures, I would write a unit test to verify that the function returns the correct owner for valid eventId inputs and properly handles invalid cases.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm web3 frontend developer who have contributed to previous repository in previous OD Hack I would love to take up on this issue

### How I plan on tackling this issue
my solution involves understanding the existing codebase, implementing the necessary function, thoroughly testing it to ensure accuracy, and finally deploying the updated smart contract.  with an ETA : at most 72 hours

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Blockchain developer with expertise in Cairo, Solidity, Rust . I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more .

### How I plan on tackling this issue
[1]=> Make event_owner function to return the event owner for a given event ID.
[2]=>Ensure the function panics for invalid event IDs.
[3]=>Write unit tests for the event_owner function, including a test to check that it panics when given a wrong event ID.
[4]=>Sir/Mam Please assign me this issue

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
i will Verify the function returns the correct event owner
Verify the function panics with the expected error message.

**Comment by shaaibu7** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Smart contract developer with strong understanding of blockchain technology with experience in building tested and scalable smart contract and Dapp on the blockchain

### How I plan on tackling this issue
Write a unit test that calls the attendee_event_details function, passing a valid event_id.

Verify that the returned EventRegistration struct contains the expected details by asserting each field matches what was stored during registration.

Ensure that the test checks if the caller has registered for the event by verifying the function returns valid details only for registered attendees.

Add a case where the caller hasn't registered for the event, asserting that an error or default value is returned.

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet.

### How I plan on tackling this issue
To test the `event_owner` function, I will first set up an event with a known owner and assert that the returned owner address matches the expected value when the function is called with the correct event ID. Additionally, I will call the function with an invalid event ID and assert that it panics, ensuring proper error handling for non-existent events.

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello @mubarak23, how would love to implement this,

### How I plan on tackling this issue
Get the event from state and return the event owner

**Comment by Abeeujah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Blockchain and Systems Engineer with extensive knowledge and skillset in Rust and Cairo, With my TDD approach to problem solving I'll be able to leverage that in ensuring the solutions I provide are logically and conceptually correct, and functions as expected.

### How I plan on tackling this issue
Given the function signature, and program requirements
Implementation
The function would panic when an invalid event_id is provided
The function returns the ContractAddress of the event Organizer
Testing
Assert the function returns the valid ContractAddress of the Event Organizer
Assert the function panics when an invalid event_id is provided

ETA 4HRs

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past.

### How I plan on tackling this issue
I will carefully implement the requested feature and use Starknet Foundry to make sure the implementation is correct.

ETA Half a day.
