### ISSUE TITLE
Function that return number event registration

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#21]
Given an event Id, return the total number of people that register for an event,

Write unit test for the function

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Mid leve Cairo Developer

### How I plan on tackling this issue
I will write a function that takes an event_id as input and retrieves the total number of registrations for that event from the relevant storage map, then ensure the function returns the count of registered users associated with the given event_id.

**Comment by mubarak23** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).
> ### My background and how it can be leveraged
> 
> Mid leve Cairo Developer
> ### How I plan on tackling this issue
> 
> I will write a function that takes an event_id as input and retrieves the total number of registrations for that event from the relevant storage map, then ensure the function returns the count of registered users associated with the given event_id.

thank you for applying to work on this issue,

all application will be consider when the ODHACK-9 start on 24th october

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hi

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Blockchain developer with expertise in Cairo, Solidity, Rust . I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more .

### How I plan on tackling this issue
[1]=>Make a function to return the total number of registrations for a given event ID.
[2]=>Write a unit test to verify the registration count for various scenarios.
[3]=>Sir/Mam Please Assign Me

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
i will Verify the function returns 0,
Verify the function returns 1,
Verify the function returns the correct count,
Verify the function ignores duplicate registrations,
Verify the function throws an error.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Am a frontend developer with experience in building and connecting smart contract to dapps. with experience in cairo and solidity smart contract testing if assigned i would be able to handle this issue

### How I plan on tackling this issue
Define the Event Structure:

In Cairo, define an event structure that holds details about the event, such as the event_id and information related to the registered users.
Create a Function to Handle Registration:

Implement a function that takes the event_id as an input.
This function should loop through a list or map of attendees linked to each event and count the number of registered people.
Emit Event Data:

During the registration process, emit an event for each registered user by associating them with the respective event_id. This event can be stored and later queried from the transaction receipt in the blockchain.
Return the Total Count:

After iterating through all the registered users for the given event_id, return the total number of attendees.
Writing Unit Tests:
Test Setup:

Create a mock setup where different events have a varying number of registered users.
Test Case for Registration:

Write a unit test to check if the function correctly identifies and counts the registered attendees for a specific event.
Boundary Testing:

Test edge cases such as an event with no attendees or an invalid event_id to ensure the function handles these scenarios correctly.
Validation of Results:

Ensure that the returned count matches the expected number of attendees for different events in the unit test.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
My background in smart contract development and testing enables me to effectively implement this functionality and ensure its accuracy and reliability through comprehensive testing.

### How I plan on tackling this issue
To implement the function that returns the total number of people registered for an event, I would define it in the smart contract, ensuring it takes the `event_id` as a parameter and retrieves the count from the event registration data structure. I would also implement the necessary logic to accurately count registered attendees.

For unit testing, I would write tests to validate the following scenarios: 
1. Correct Count:Ensure that the function returns the correct total number of registered attendees for a given event.
2. No Registrations: Verify that the function returns zero when there are no registrations for the specified event.
3. Invalid Event ID: Test how the function handles invalid event IDs, ensuring appropriate error handling.

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello @mubarak23, how would love to implement this

### How I plan on tackling this issue
Get the event from state, compute the total registrations, return the value

ETA: 4hrs

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### How I plan on tackling this issue
I will implement a function called `total_event_registrations` that accepts an `event_id` as input and returns the total number of people registered for that specific event. This will be achieved by reading the `event_details` mapping and accessing the `total_register` field associated with the event. I will then write unit tests to ensure the correctness of this function. The tests will cover various scenarios: verifying the correct registration count after users register, testing for zero registrations when no one has signed up, and handling non-existent event IDs to ensure proper functionality.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past.

### How I plan on tackling this issue
I will carefully implement the requested feature and use Starknet Foundry to make sure the implementation is correct.

ETA Half a day.

**Comment by mubarak23** [comment]
@Abeeujah can you provide an update on this issue
