### ISSUE TITLE
Test for add_event Function

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#22]
currently we have test for check that an event is added,

write two more test for
- event count increase
- event is emitted 
Provide an ETH

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a frontend developer with experience in writing smart contracts using solidity and cairo. I have written test case for previous projects in previous hackathon 

### How I plan on tackling this issue
The test to handle both events will cover 

The state b4 and after the event

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Mid level Cairo Developer

### How I plan on tackling this issue
I will write the test to check if the event count increases by one after adding a new event then write the test to verify that the correct event is emitted upon adding an event, ensuring the emitted event details match the expected values.

**Comment by casweeney** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.

### How I plan on tackling this issue
Looking at the storage struct, I can see an even count, I will write a test that creates an event, then I will assert that the value of event_counts increased, I will also test for emitted event.

**Comment by No-bodyq** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a web3 and full-stack developer with experience in writing unit tests in cairo. I have written tests for other projects on the onlydust website: Here is my profile: https://app.onlydust.com/u/No-bodyq

### How I plan on tackling this issue
I will write unit tests to check the amount of events before and after the function call to verify there was an increase in the event count and make sure the tests were emitted, ensuring the details match the values expected

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I have a background in developing decentralized apps with Cairo,  smart contracts on the StarkNet blockchain. I can efficient, scalable smart contracts that utilize zero-knowledge proofs and am familiar with Cairo testing to ensure my contracts meet functionality and security standards. 

### How I plan on tackling this issue
To address the issue, I would start by reviewing the existing code to understand event handling and examining previous tests for insights. 
With this knowledge, I would create detailed tests to verify state changes and event emissions, ensuring state variables update correctly and the right events are triggered with the appropriate parameters. This will ensure that my tests comprehensively validate the application's functionality.

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a  Blockchain developer with expertise in Cairo, Solidity, Rust . I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more .

### How I plan on tackling this issue
[1]=>Write a test to confirm that the event count increases when a new event is added.
[2]=>Create another test to verify that the appropriate event is emitted when an event is successfully added.
[3]=>Ensure that both tests are integrated with the existing test suite for seamless execution.
[4]=>Please assign Me Sir /mam

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
I will Get the initial event count,
Add an event.
Verify the event count has increased by 1,
Next Add an event
Verify the EventAdded event is emitted with the correct arguments (eventId, owner, amount, eventType).

**Comment by Kaminar-i** [comment]
### My Tech Background

I’m a blockchain developer highly experienced in Solidity and Python. Recently, I’ve been diving into Cairo and the Starknet ecosystem, building decentralized applications. I’m skilled in frontend integrations with React and Wagmi, and I’m comfortable using tools like Hardhat and Scarb. I’m quick to adapt to new tech and ready to work.

### How I Plan on Tackling This Issue

To tackle the problem of testing event count increase and emission, I would start by checking the initial count of events in the contract before any interaction, essentially setting a baseline. Then, I would trigger the function that is supposed to add or create an event. After the function is executed, I would query the contract again to retrieve the new event count. At this point, the goal is to compare the two values—the event count before and after—to ensure that it has incremented, confirming that the contract is properly tracking new events.

For testing the event emission, I would execute the function responsible for emitting the event. While the function runs, I’d monitor the output for any emitted events. The focus would be to verify that the specific event we expect is triggered and that it carries the correct values or parameters, depending on the contract's logic. This ensures that not only does the function work, but it also communicates the right data externally via events, which is important for dapp functionality and external interactions.

By verifying both the state change (event count) and the interaction (event emission), I’d cover key aspects of how the contract behaves during event creation and communication.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
To enhance the test coverage for the add_event function in the Events contract, I will implement two additional tests alongside the existing test that checks if an event is added successfully.

Test for Event Count Increase: This test will verify that the event_counts storage variable increments correctly each time an event is added. After calling the add_event function, I will check that the count has increased by one compared to its value before the function call.

Test for Event Emission: This test will ensure that the NewEventAdded event is emitted correctly with the expected parameters when a new event is successfully added. I will capture the emitted events and check that the NewEventAdded event is present and matches the expected values.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and will love to work on this issue. please assign.

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet.

### How I plan on tackling this issue
To tackle this issue, I will first write a test to verify that the event count increases correctly when a new event is added. This will involve capturing the current event count, adding a new event, and asserting that the count has incremented by one. Next, I will create another test to ensure that the appropriate event is emitted when the event is added. This will involve calling the function that adds the event and verifying that the emitted event matches the expected type and parameters.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by Abeeujah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Blockchain and Systems Engineer with extensive knowledge and skillset in Rust and Cairo, With my TDD approach to problem solving I'll be able to leverage that in ensuring the solutions I provide are logically and conceptually correct, and functions as expected.

### How I plan on tackling this issue
I would write unit tests that simulate an event addition and then check
- Event Count Increases
- Event is emitted

ETA 4HRs

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I have contributed to several Cairo projects on OnlyDust and I've worked on very similar issues in the past.

### How I plan on tackling this issue
I will carefully write the required tests using Starknet Foundry.

ETA Half a day.

**Comment by jorgezerpa** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I'm a fullstack developer with 4 years of experience building web applications. I have good experience implement Starknet contracts testing 

### How I plan on tackling this issue
I will work into tests/test_contract.cairo file

Here is a blueprint of the functions event_count_increase and  event_is_emmited that I will create for testing:

```
// *************************************************************************
//                              Events TEST
// *************************************************************************
use core::option::OptionTrait;
use core::starknet::SyscallResultTrait;
use core::result::ResultTrait;
use core::traits::{TryInto, Into};
use starknet::{ContractAddress};

use snforge_std::{
    declare, start_cheat_caller_address, stop_cheat_caller_address, ContractClassTrait,
    DeclareResultTrait,
};

use chainevents_contracts::interfaces::IEvent::{IEventDispatcher, IEventDispatcherTrait};


const USER_ONE: felt252 = 'JOE';
const USER_TWO: felt252 = 'DOE';

// *************************************************************************
//                              SETUP
// *************************************************************************
fn __setup__() -> ContractAddress {
    // deploy  events
    let events_class_hash = declare("Events").unwrap().contract_class();

    let mut events_constructor_calldata: Array<felt252> = array![];
    let (event_contract_address, _) = events_class_hash
        .deploy(@events_constructor_calldata)
        .unwrap();

    return (event_contract_address);
}

#[test]
fn test_add_event() {
    let event_contract_address = __setup__();

    let event_dispatcher = IEventDispatcher { contract_address: event_contract_address };

    start_cheat_caller_address(event_contract_address, USER_ONE.try_into().unwrap());
    let event_id = event_dispatcher.add_event("bitcoin dev meetup", "Dan Marna road");
    assert(event_id == 1, 'Event was not created');
    stop_cheat_caller_address(event_contract_address);
}

#[test]
fn event_count_increase() {
    // 1. Call a certain amount times the add_event_function
    // 2. Between the calls and after all of them, assert the event_counts property to the correspondant value 
}

#[test]
fn event_is_emmited() {
    // 1. Call add_event_function
    // 2. Once called, I will test the event emition using starknet::testing::pop_log(contract_address) functionality, for example:
    // 
    //   assert_eq!(
    //       starknet::testing::pop_log(contract_address),
    //       Option::Some(Event::CounterIncreased(NewEventAdded { name, location, event_onwer }))
    //   );
}
```

## ETA: 2h
