### ISSUE TITLE
Upgrade event Function

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#23]
as an event owner, i should be able to update my event to paid event
`
fn upgrade_event(ref self: TContractState, event_id: u256, paid_amount: u256);`

update event details with amount, set the type to event_type: EventType::Paid  and emit UpgradedEvent event

write unit test for the following edge case
- only event owner can upgrade event
- check for the event_type is paid on the EventDetails 

Provide an ETH

**Comment by codeZe-us** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Mid - level Cairo Developer

### How I plan on tackling this issue
1. Check Ownership: I will make sure event owner can call the update function.
2. Update Event: I will modify event details to set it as a paid event and specify the fee.
3. Emit Event: Then, I will log the update with an event emission.

**Comment by PoulavBhowmick03** [comment]
hi! gm. I just wanted to know and confirm that the comments made from the start of odhack will be considered right? thanks!

**Comment by mubarak23** [comment]
> hi! gm. I just wanted to know and confirm that the comments made from the start of odhack will be considered right? thanks!

Yes

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I have a strong background in web development and blockchain integration, focusing on decentralized applications. I know how to use React and Node.js, along with developing smart contracts. This helps me create smooth and easy-to-use experiences for users. I have also worked on projects featuring user authentication and paid events.

### How I plan on tackling this issue
To help event owners update their events to paid status, I will review the current event management system. Then, I will add a feature that allows them to switch the status to "paid" and ensure this is reflected in the backend. After updating the event, I will show notifications to users and test everything to ensure it runs smoothly.

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a web3 developer

### How I plan on tackling this issue
as an event owner, i should be able to update my event to paid event

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Blockchain developer with expertise in Cairo, Solidity, Rust, and Foundry. I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more .

### How I plan on tackling this issue
[1]=>Implement the upgrade_event function to change the event type to paid and emit UpgradedEvent.
[2]=>Write unit tests to ensure only the event owner can upgrade the event.
[3]=>Verify that the event type is set to paid in EventDetails.
[4]=>Provide an Ethereum address for testing if needed.
[5]=>Sir Please assign me this issue ,

**Comment by Gianfranco99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged

I have been a developer for over 4 years and have been contributing to the Starknet ecosystem for more than a year. My recent contributions include work on cairo-lint and scaffold-starknet. I’m eager to participate in this project as I see a lot of potential in it and believe it adds valuable functionality to the Starknet ecosystem.

### How I plan on tackling this issue
 I will write a test to ensure that only the event owner can call the upgrade_event function.

After the event is upgraded, I will check that the event_type is correctly set to EventType::Paid and that the paid amount is updated in the event details.

**Comment by MullerTheScientist** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a full-stack developer with experience in QA testing and languages like Python, Cairo, Solidity, React, and JavaScript.

### How I plan on tackling this issue
First, I would implement the upgrade_event function in the smart contract.
Next, I would write unit tests for the upgrade_event function. I would test the edge case where only the event owner can upgrade an event
i will Create an event with an owner,
Attempt to upgrade the event using a non-owner account,
Verify that an error is thrown with the expected message,
Upgrade the event using the owner account,
Verify that the event type is updated to Paid,
Verify that the UpgradedEvent is emitted with the correct arguments.

**Comment by shaaibu7** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Smart contract developer with strong understanding of blockchain technology with experience in building tested and scalable smart contract and Dapp on the blockchain.

### How I plan on tackling this issue
Implement the upgrade_event function to check if the caller is the event owner before updating the event.

Update the event's details by setting event_type to EventType::Paid and the provided paid_amount.

Emit the UpgradedEvent event with relevant details.

In the unit test, verify that only the owner can upgrade the event, and check that the event_type is updated to Paid in EventDetails.

**Comment by Lukman-01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
Hello! My name is Lukman, and I am a passionate Smart Contract Developer with two years of experience in writing smart contracts. My hands-on experience spans various blockchain platforms, including Ethereum and Starknet.

### How I plan on tackling this issue
To approach testing the `upgrade_event` function, I will first create a test scenario where an event owner attempts to upgrade their event with a specified paid amount and assert that the event type is updated to `EventType::Paid` in the `EventDetails`. Additionally, I will include a test to ensure that an attempt to upgrade the event by a non-owner results in a failure, confirming that only the event owner has the authority to perform the upgrade.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
 I am a frontend and blockchain developer .My background in smart contract development and testing equips me to effectively implement and validate this functionality.

### How I plan on tackling this issue
To implement the `upgrade_event` function, I would define it in the smart contract to allow the event owner to update the event to a paid event by specifying the `event_id` and `paid_amount`. This function would update the event details to set the type to `EventType::Paid` and emit an `UpgradedEvent` event. I would then write unit tests to ensure that only the event owner can upgrade the event and to verify that the `event_type` is correctly set to paid in the `EventDetails`. Additionally, I would ensure the necessary ETH is provisioned in the testing environment.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will implement the upgrade_event function, enabling an event owner to convert their event into a paid event by specifying the event_id and the paid_amount. This function will not only update the event details but also set the event_type to EventType::Paid. Additionally, it will emit an UpgradedEvent to notify the relevant parties about this change.

To ensure the reliability and security of this implementation, I will write comprehensive unit tests that cover critical edge cases. One of these tests will verify that only the event owner has the authority to upgrade the event. This is crucial for maintaining event ownership integrity and preventing unauthorized changes. I will check that the caller's address corresponds with the registered owner of the event, ensuring that no one else can make this modification.

Another test will focus on validating that the event_type is updated correctly to reflect the change to Paid. This will involve checking the EventDetails after the upgrade to confirm that it reflects the expected type. Ensuring that the event type is accurately updated is essential for the functionality of the application and for users' understanding of event statuses.

By addressing these aspects, I will create a robust implementation of the upgrade_event function that not only meets functional requirements but also adheres to best practices for security and data integrity. I appreciate the opportunity to work on this task and will provide the completed implementation and tests within the next few days. My ETA is 5days.

**Comment by mubarak23** [comment]
@Immanuelolivia1 can you provide an update on this issue
