### ISSUE TITLE
[BACKEND] setup the backend with express, postgre and knex.js ORM

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#26]
Setup backend with the following structure
- basic server setup
- POST and GET route for Registered event
-  Save emitted event data base on this [structure](https://github.com/mubarak23/chainevents-contracts/blob/main/src/events/events.cairo#L49) on the database model.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/chaineventts).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the task requirement, i can very much handle this task.
