### ISSUE TITLE
Refactor Attendee Registration count

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#39]
After a user has register for an event, we should update a map, that show the number of user that register for the event

i.e  `attendee_event_registration_counts: Map<u256, u256>`

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed  to  this  project  in odhack 9   .   please /assign  this issue .
Thank You

**Comment by blessingbytes** [comment]
I’m interested in this one.

**Comment by Benjtalkshow** [comment]
I’m interested in this one.

**Comment by GideonBature** [comment]
I’d like to work on this.

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I should be able to send my first PR within 48 hrs. 

Thank you!

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by Michaelkingsdev** [comment]
I’d like to resolve this.

**Comment by BrunoAmbricca** [comment]
I would like to do this issue

**Comment by Kaminar-i** [comment]
Could I take on this issue?

**Comment by mimiprosper** [comment]
Is it okay if I take this?  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 2 days.

**Comment by ptisserand** [comment]
I'm a cairo developer with several contributions to ark project, art peace, shinigami, konoha, OZ
I will do TDD for this task: write unit test and update source code to make it pass.

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend dev and blockchain dev
i would really love to contribute to your project 
kindly assign :)

**Comment by casweeney** [comment]
## Tacking this issue

- Given that I understand this code base, I will refactor the `attendee_evrnt_registration_count` to meet the requirements specified.

**Comment by mimisavage** [comment]
Can I take this issue?

**Comment by hossamanany** [comment]
Can I take this from here?

**Comment by Emrys02** [comment]
Could I grab this task?

**Comment by Psalmuel01** [comment]
Could I grab this task? I can very well refactor the count.

**Comment by mubarak23** [comment]
@Psalmuel01 What is the update on this tasks

**Comment by Psalmuel01** [comment]
@mubarak23 on it now
