### ISSUE TITLE
Setup apibara for indexing Contract Events - Backend

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#44]
Setup apibara for indexing event on the backend.

this way each event emitted will be handle and save on the db 
The setup will handle all external contract function.

**Comment by ikemHood** [comment]
I'd be happy to do this.

**Comment by Unickhub** [comment]
Is this issue still available?

**Comment by BrunoAmbricca** [comment]
I would like to do this issue

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many cairo ,rust  projects like chainevents , arkprojects etc  .   please /assign  this issue .
Thank You

**Comment by saimeunt** [comment]
Hey I've already worked with apibara on another project and I'd like to try this one please!
https://github.com/walnuthq/starkflare-indexer
