### ISSUE TITLE
Endpoint for fetching all Open events - Backend

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#45]
Endpoint that fetch all event Registered on the system in a paginated list form.

**Comment by jaykayudo** [comment]
@mubarak23  Can I work on this as soon as odhack starts ?

**Comment by abdegenius** [comment]
Can I start working on this? I can comfortably handle this issues

**Comment by anonfedora** [comment]
Hi I'm Eleazar, a fullstack Blockchain developer (Backend heavy - expressjs, nestjs, Cairo),
I will implement a fetchAllEvents with pagination .

ETA: 48 Hours

**Comment by No-bodyq** [comment]
Could I take a shot at this?

**Comment by PabloVillaplana** [comment]
Hi, I'm Juan Pablo Villaplana from Dojo Coding, I'd like to contribute to this ChainEvents issue

We create an endpoint with its respective validations to be able to obtain all active events

**Comment by Akshola00** [comment]
Can I work on this, please?

**Comment by Amarjeet325** [comment]
Can I take this issue?

**Comment by blessingbytes** [comment]
pls, i will love to work on this issue . I promise to deliver

**Comment by BrunoAmbricca** [comment]
I would like to do this issue

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  contributed many Rust ,Cairo  projects like chainevents , arkprojects , starknet  etc  .   please /assign  this issue .
Thank You

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by Gianfranco99** [comment]
Hello, I can solve this issue easily, I have already been contributing to this project and I would like to continue being part of it!

**Comment by esladan** [comment]
I’d like to work on this.

**Comment by mimisavage** [comment]
Let me try this one!

**Comment by hossamanany** [comment]
Is it okay if I tackle this?

**Comment by saimeunt** [comment]
Hey I'd like to work on this one, see my past experiences here: https://app.onlydust.com/u/saimeunt

**Comment by caxtonacollins** [comment]
i will love to work on this please assign me

**Comment by GideonBature** [comment]
I'd love to give this a go.

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I will send my first PR within 48 hrs. 

Thank you!

**Comment by Villarley** [comment]
Hi, I’m Santiago Villarreal Arley, a proactive and communicative developer with experience in both front-end and back-end Web3 development. I’m a proud member of Dojo Coding and have worked on various projects built on StarkNet and Stellar, where I actively contributed to creating scalable and efficient solutions. I also won a Web3 hackathon Buildathon for my work on BuildMyEvent, an open-source blockchain project focused on solving real-world challenges and integrating useful features.

I estimate this will take 2–3 days to complete.

This is how I would tackle this issue:

Read all the indications to build exactly what you want
Implement a service function to fetch all registered events with pagination support.
Add a GET /events endpoint in the controller to handle requests and return the paginated list of events.
Ensure proper testing of the endpoint to validate functionality
This would be my first contribution, and with my strong TypeScript background, I’m confident I'll be able to deliver a great solution.

**Comment by devJaja** [comment]
Hey
To create an endpoint for fetching all open events, I will define a route (e.g., GET /api/events/open), then query the database for events matching the "open" criteria (such as status: 'open' or future dates), and then return the results in JSON format using a backend framework like Express.
I'd like to handle this task.

**Comment by morelucks** [comment]
Hello,  
I am Kamshak Lucky Isuwa.
I’m excited to contribute to this project by developing the API endpoint to fetch all registered events in a paginated list format.

**Why I’m a Good Fit**:
- Experienced in backend development using **JavaScript (Express.js)** and **Python (Django)**.
- Skilled in building RESTful APIs with robust pagination, database optimization, and clear documentation.
- Familiar with relational and NoSQL databases, ensuring scalable solutions for large datasets.

**Plan**:
1. Create an efficient database query to retrieve and paginate event data.
2. Implement API endpoint as per the stack preference.
3. Add input validation and detailed API documentation (Swagger/Postman).

Looking forward to collaborating and contributing to this project!

**Comment by martinvibes** [comment]
hey sir i would like to work on this issue 
i'm a frontend dev, blockchain and a technical writer 
kindly assign and i would get to work right away

**Comment by Supa-mega** [comment]
I'd love to give this a go.

**Comment by Aditya-040** [comment]
May I be assigned to this?

**Comment by KevinMomanyi** [comment]
I’d like to resolve this.

**Comment by KevinLatino** [comment]
Hello @mubarak23! My name is Kevin Latino, and I'm a backend developer and active open-source contributor. I'm a member of Dojo Coding, a thriving Web3 community in Costa Rica. I have experience with Node.js, Express, and TypeScript, as well as building and integrating RESTful APIs, managing databases like PostgreSQL and MongoDB, and implementing scalable architectures. Recently, I won the LATAM Hackathon hosted by Base and have contributed to projects within ecosystems like Starknet and Stellar.

I would create a route that accepts page and per_page as query parameters, call the paginateData method from the Event model, and return the data in a JSON response. The response would include events, total count, current page, and total pages, ensuring proper validation and error handling.

**Comment by emarc99** [comment]
Can I tackle this one? I can do it in 2 days max.

**Comment by olisaagbafor** [comment]
Can I take care of this issue?

**Comment by DotworldX** [comment]
Mind if I take this issue?

**Comment by CEOliam** [comment]
I'd love to give this a go.

**Comment by anonfedora** [comment]
Hi ser @mubarak23, I'm available to fix this issue. I'm a backen heavy (Nestjs, expressjs) developer.

**Comment by Abeeujah** [comment]
Hello Good Evening, I'm a Full Stack Engineer proficient in building scalable systems, Can I work on this?
