### ISSUE TITLE
Endpoint for fetching single event details - Backend

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#46]
Using an event_id, fetch event details, include all attendee that register for the event.

**Comment by codebestia** [comment]
@mubarak23  May i try my hand on this ?

**Comment by estherbreath** [comment]
@mubarak23 I would like to work on this issue, please

**Comment by ikemHood** [comment]
Can I be assigned to this?

**Comment by PabloVillaplana** [comment]
Hi, I'm Juan Pablo Villaplana , I'd like to contribute to this ChainEvents issue. I have experience working with ticket offices and I think I can help a lot on this project.

**Comment by Akshola00** [comment]
I'd like to take this issue.

**Comment by estherbreath** [comment]
I am a smart contract developer in Solidity and Cairo, also specialized in frontend and backend I would like to work on this issue.

I will use the following approaches to tackle the issue

- implement a getEventDetails function that takes an event_id as input.
- fetch event details using the existing EventDetailsStruct mapping. To include registered attendees,
- Create a new function getRegisteredAttendees that iterates through the EventRegisterUser mapping for the given event ID.

**Comment by Amarjeet325** [comment]
Hi, I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly assign this issue/task to me? Thank you

**Comment by Benjtalkshow** [comment]
Can I start working on this?

**Comment by Cyberking99** [comment]
Hello, with my experience in backend (nodejs, expressjs, and nestjs) with sequelize and knex, I can create an endpoint to fetch an event details using the event_id. The event details will also include all the attendees that have registered for that particular event.

In addition, proper validation will be applied.

**Comment by BrunoAmbricca** [comment]
I would like to do this issue

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by Gianfranco99** [comment]
Hello, I can solve this issue easily, I have already been contributing to this project and I would like to continue being part of it!

**Comment by mimisavage** [comment]
I’d like to resolve this.

**Comment by saimeunt** [comment]
Hey I'd like to work on this one, see my past experiences here: https://app.onlydust.com/u/saimeunt

**Comment by caxtonacollins** [comment]
May I take care of this?

**Comment by akintewe** [comment]
I’d like to help with this.

My name is akintewe, a Software Engineer with experience building applications and backend structures , i have experience in Javascript and  Cairo. If given this issue, I should be able to send my first PR within 24 hrs.

Thank you! :)

**Comment by GideonBature** [comment]
Can I jump on this task?

My name is Gideon Bature, a Software Engineer with experience building Starknet based smart contracts, using Cairo. If given this issue, I will send my first PR within 48 hrs. 

Thank you!
