### ISSUE TITLE
Write an nft contract - Contracts

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#48]
The contract should have  the following function `mint_nft` and `burn_nft` 

The contract should have following storage structs.

```
	#[storage]
	struct Storage {
    	#[substorage(v0)]
    	erc721: ERC721Component::Storage,
    	#[substorage(v0)]
    	src5: SRC5Component::Storage,
    	last_minted_id: u256,
    	mint_timestamp: Map<u256, u64>,
    	user_token_id: Map<ContractAddress, u256>,
    	event_id: u256
	}
```

**Comment by ikemHood** [comment]
I would like to take on this as soon as the od hack starts

**Comment by Mystic-Nayy** [comment]
Could I be assigned to this?
I am a web3 developer 
I will write the contract to have the follow

**Comment by Amarjeet325** [comment]
Could I grab this task?

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have  already  contribute  this project in odhack 9.   please /assign  this issue .
Thank You

**Comment by Mystic-Nayy** [comment]
May I pick this up?
I am a web3 developer
I will update the following functions mint_nft and burn_nft in the contract

**Comment by CollinsC1O** [comment]
Hello @mubarak23 Can I take care of this issue?

**Comment by omsant02** [comment]
i would like to take this issue @mubarak23 

i am a new contributor to this repo and want to start my contribution journey with Chainevents-contracts 
ETA : 2 days
Thank you

**Comment by BrunoAmbricca** [comment]
I would like to do this issue

**Comment by SoarinSkySagar** [comment]
May i work on this issue @mubarak23?

I am a cairo dev and a regular os contributor at @keep-starknet-strange.

eta: 3 days

**Comment by ryzen-x** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
 please /assign  this issue .
Thank You

**Comment by mimiprosper** [comment]
I'd like to handle this task.  Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 2 days.

**Comment by MullerTheScientist** [comment]
please can i address this task

**Comment by vestor-dev** [comment]
hey sir I'd like to handle this task.
i'm a frontend developer and blockchain dev
i would really love to contribute to your project 
kindly assign :)

**Comment by jorgezerpa** [comment]
hello! I'm a fullstack Blockchain developer. I had contributed to projects like Ark, Landver and GoStarkMe. 

This is how I plan to tackle this issue:
- Create a new Contract called EventNFT 
- I will use openZeppellin to implement the erc721 functionalities 

Here is an example of an NFT contract which I have worked on for [Landver](https://github.com/NoshonNetworks/landver/blob/main/land_registry/src/land_nft.cairo). This is a very similar requirement, so I can use it as base to deliver ASAP. 

### ETA: 5-6h. Could be ready no later than tomorrow.

I'm attentive!!

**Comment by jorgezerpa** [comment]
hello! I'm a fullstack Blockchain developer. I had contributed to projects like Ark, Landver and GoStarkMe.

This is how I plan to tackle this issue:

Create a new Contract called EventNFT
I will use openZeppellin to implement the erc721 functionalities
Here is an example of an NFT contract which I have worked on for Landver. This is a very similar requirement, so I can use it as base to deliver ASAP.

ETA: 5-6h. Could be ready no later than tomorrow.
I'm attentive!!

**Comment by saimeunt** [comment]
Hey I have experience working with NFT contracts in Cairo, can I implement this one please?
https://github.com/carbonable-labs/cairo-erc-7498

**Comment by sandragcarrillo** [comment]
Hi, I would love to contribute to this issue. I have been learning Cairo for the past 3 months and been creating guides for Starknet contracts during my internship at Nethermind (already completed), including ERC-720 and ERC-20. I started to contribute to Open Source projects during this ODHack, this issue would be an amazing opportunity to start my path as open source contributor in the Starknet ecosystem.
