### ISSUE TITLE
From the event nft contract  add more function

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#49]
Add the following functions and write unit test for them 

get_user_token_id

name

symbol

Token_uri

**Comment by blessingbytes** [comment]
Can I try solving this issue? i promise to deliver

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity  and also in web development.
I have already  contributed to this project in odhack 9    .   please /assign  this issue .
Thank You

**Comment by ooochoche** [comment]
I could perform the required task on this issue if assigned to me

**Comment by CollinsC1O** [comment]
Hello @mubarak23 I would love to work on this issue, please assign

**Comment by Immanuelolivia1** [comment]
May I take care of this?

**Comment by MrRoudyk** [comment]
May I handle this issue?

**Comment by SoarinSkySagar** [comment]
May i work on this issue @mubarak23?

I am a cairo dev and a regular os contributor at @keep-starknet-strange.

eta: 3 days

**Comment by mimiprosper** [comment]
Could I take over this issue? Am a web 2 frontend developer, a solidity smart contract developer/auditor and a cairo smart contract developer. Am a graduate of Starknet Cairo Bootcamp. I have successfully done tasks assigned to me in OnlyDust. If assigned this i would complete it within 2 days.

**Comment by MullerTheScientist** [comment]
Hello please can i address this issue

**Comment by ryzen-xp** [comment]
Hi, I am a proficient Blockchain developer with expertise in Cairo, Rust, and Solidity. I also contributed to this project during ODHack 9.  
To tackle this issue, I will:==> 
1. Implement the required functions (get_user_token_id, name, symbol, Token_ur`).  
2. Write comprehensive unit tests for each function, covering all edge cases.  
3. Optimize the contract to ensure gas efficiency for the new functions.  
Please assign this issue to me. Thank you!

**Comment by saimeunt** [comment]
Hey I have experience working with NFT contracts in Cairo, can I implement this one please?

**Comment by Gianfranco99** [comment]
Hello, I can solve this issue easily, I have already been contributing to this project and I would like to continue being part of it!

**Comment by bruhhgnik** [comment]
Hey @mubarak23, i can get done with this in 24 hours, let me try this!

**Comment by Aditya-040** [comment]
I'd love to work on this!

**Comment by mimisavage** [comment]
I’d love to work on this task.

**Comment by codeZe-us** [comment]
I can take this, it's straight forward to work on. 
ETA: 5 hours

**Comment by Emrys02** [comment]
Let me try this one!

**Comment by EstherLavender** [comment]
Can I contribute to this one?
