### ISSUE TITLE
Upgradable Function

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#50]
Using open zeppelin implementation, write a function that update the contract

**Comment by Iwueseiter** [comment]
Hi @mubarak23 can I work on this?

**Comment by manlikeHB** [comment]
Hi, I am Cairo Developer with great experience. I am familiar with implementing Upgradable in a contract.

**Comment by Shalomnze** [comment]
Could I grab this task?
i can use OpenZeppelin's UUPS or Transparent Proxy pattern. Since OpenZeppelin already provides the core upgrade mechanism i do not neccessary need to write the upgrade function itself. Instead i would ensure the contract is compatible with the upgradeable structure.

**Comment by martinvibes** [comment]
hey sir i would like to work on this issue 
i'm a frontend dev, blockchain 
kindly assign and i would get to work right away

**Comment by Supa-mega** [comment]
May I pick this up?
