### ISSUE TITLE
Private Funtion that deploy eventNft contract

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#51]
write a private function that use syscall to deploy eventNFT contract

**Comment by ikemHood** [comment]
Let me try this one!

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of amazing projects. I would like to work on this.

**Comment by martinvibes** [comment]
hey sir i would like to work on this issue 
i'm a frontend dev, blockchain and a technical writer 
kindly assign and i would get to work right away

**Comment by Supa-mega** [comment]
Can I take this issue?

**Comment by byteZorvin** [comment]
Hi sers, I would like to work on this, New contributor.
PoW: [Bridge contracts](https://github.com/karnotxyz/starknet_bridge)

**Comment by casweeney** [comment]
I can work on this issue.

### ETA: 5 hours

**Comment by emarc99** [comment]
I'd be happy to do this.

**Comment by CEOliam** [comment]
Can I try solving this issue?

**Comment by vestor-dev** [comment]
I’d like to resolve this.
@mubarak23 please kindly assign

**Comment by 0xprivateChaos** [comment]
Could I take on this issue?

**Comment by casweeney** [comment]
## Applying via OnlyDust

### Tackling this issue:
- I will create an `InternalImpl` with a `generate_trait` attribute.
- I will create a function `deploy_event_nft()` inside the `InternalImpl` block.
- I will then implement the fuction to deploy an NFT contract using a syscall.

## ETA: 4 - 6 hours tops.
