### ISSUE TITLE
Documentation for Contract 

### ISSUE THREAD

**Issue by mubarak23** [mubarak23/chainevents-contracts#52]
write a full documentation for all contract functions and implementation

**Comment by Iwueseiter** [comment]
Hi @mubarak23 can I tackle this?

**Comment by ikemHood** [comment]
Could I take over this issue?

**Comment by Xaxxoo** [comment]
Hi Mubarak, Let me try this.

**Comment by Shalomnze** [comment]
Is it okay if I take this? 
i would procees by analysing the contract and then writing the purpose of the contract, i would then proceed to document each functions that is the description, parameters, modifiers and more. i would then describe the state variables before talking about the deployment process while doing that i would take note if the contract is upgradable before talking about how to upgrade the contract and tools needed before i proceed to testing scenarios and secrutiry issues

**Comment by martinvibes** [comment]
hey sir i would like to work on this issue 
i'm a frontend dev, blockchain and a technical writer 
i'd make sure to write a comprehensive and precise documentation for all contracts and implementation

kindly assign and i would get to work right away

**Comment by Kingsuite** [comment]
Let me handle this issue!

I am a technical writer and i have experience in documenting code base. kindly assign

ETA <= 24hrs

**Comment by Supa-mega** [comment]
Could I try solving this?

**Comment by 3th-Enjay** [comment]
Can I start working on this?

**Comment by chigozzdevv** [comment]
I’d love to work on this task. I'm a well-versed technical writer. You can check my portfolios:
Clippings.me/chigozzdev
Medium.com/@chigozzdev
Chigozzdev.hashnode.com
